Aaron/create movies
ZacharyEllixson/itsc-3155-module-9-assignment pull request #1
Opened 2023-03-19 02:03 UTC by ZacharyEllixson

2023-03-19 03:20 UTC, joselara22 requested changes
Everything looks good.

2023-03-19 03:20 UTC, joselara22 commented on app.py
> +    rating = request.form['selectRating']
Have you considered using request.form.get() so an exception isn't thrown if the name is ever not found?

2023-03-21 23:09 UTC, WKirklandJr commented on app.py
> +    print(movie_name, director_name, int(rating))
Good idea printing it out to verify that the code is working

2023-03-21 23:24 UTC, WKirklandJr reviewed
Looks good just confirm with others

2023-03-21 23:24 UTC, WKirklandJr commented on templates/create_movies_form.html
Is there a reason for the aria-desribedby attribute? Were you planning to reference it later?

2023-03-21 23:39 UTC, merged

2023-03-23 00:31 UTC, alobo2 commented on templates/create_movies_form.html
Ooh I was using my previous html code and totally forgot to take out that attribute and id, nice catch👍

I've now removed it.