Edit pt1
ZacharyEllixson/itsc-3155-module-9-assignment pull request #3
Opened 2023-03-21 23:06 UTC by WKirklandJr

Started adding functionality for the edit / update part of the code

2023-03-21 23:53 UTC, ZacharyEllixson requested changes

2023-03-21 23:53 UTC, ZacharyEllixson commented on tests/e2e/test_edit_movie_page.py
> +    assert response.status_coude == 200
There's a typo.

2023-03-21 23:54 UTC, WKirklandJr commented on tests/e2e/test_edit_movie_page.py
> +    assert response.status_coude == 200
true that, good catch!

2023-03-22 00:05 UTC, ZacharyEllixson approved these changes

2023-03-22 00:05 UTC, merged